<?php
$pcaSettings = $block->getSettingsHelper();
$pcaAccCode = $pcaSettings->getAccountCode();
$pcaCustomJSBack = $pcaSettings->getCustomJavaScriptBack();
?>

<?php if ($pcaAccCode): ?>

    <script type="text/x-magento-init">
        {
            "*": {
                "Loqate_Tag/js/pca-customer": {
                    "pcaAccCode": "<?= /* @noEscape */ $pcaAccCode; ?>"
                }
            }
        }
    </script>

    <script type="text/javascript">
        <?php if (/* @noEscape */ $pcaCustomJSBack) { echo $pcaCustomJSBack;} ?>
    </script>

<?php endif; ?>

